"""business settings stores and registers"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c491465f4162"
down_revision = "cbb319198c91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("opening_hours", sa.String(length=500), nullable=False),
        sa.Column("receipt_name", sa.String(length=160), nullable=False),
        sa.Column("receipt_footer", sa.String(length=500), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Z0-9][A-Z0-9_-]{0,19}$'", name="ck_store_code"),
        sa.CheckConstraint("length(btrim(name)) > 0", name="ck_store_name"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_store_org_code"),
    )
    op.create_index(op.f("ix_stores_organization_id"), "stores", ["organization_id"], unique=False)
    op.create_table(
        "registers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Z0-9][A-Z0-9_-]{0,19}$'", name="ck_register_code"),
        sa.CheckConstraint("length(btrim(name)) > 0", name="ck_register_name"),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "code", name="uq_register_store_code"),
    )
    op.create_index(op.f("ix_registers_store_id"), "registers", ["store_id"], unique=False)
    op.add_column(
        "auth_audit_events", sa.Column("target_type", sa.String(length=30), nullable=True)
    )
    op.add_column("auth_audit_events", sa.Column("target_id", sa.Uuid(), nullable=True))
    op.add_column(
        "auth_audit_events",
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "auth_sessions", sa.Column("step_up_expires", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "organizations",
        sa.Column(
            "contact_email", sa.String(length=254), nullable=False, server_default=sa.text("''")
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("phone", sa.String(length=40), nullable=False, server_default=sa.text("''")),
    )
    op.add_column(
        "organizations",
        sa.Column("currency", sa.String(length=3), nullable=False, server_default=sa.text("'NPR'")),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "timezone",
            sa.String(length=80),
            nullable=False,
            server_default=sa.text("'Asia/Kathmandu'"),
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "receipt_footer", sa.String(length=500), nullable=False, server_default=sa.text("''")
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("configured", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "organizations",
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    for column in (
        "contact_email",
        "phone",
        "currency",
        "timezone",
        "receipt_footer",
        "configured",
        "version",
    ):
        op.alter_column("organizations", column, server_default=None)
    # Never promote ordinary readers. Only active, unchanged legacy owner memberships
    # with an explicit provisioning/signup audit record receive the new capability.
    op.execute("""
        UPDATE memberships AS m
        SET permissions = array_append(m.permissions, 'organization.setup')
        WHERE m.active AND m.permissions = ARRAY['organization.read']::varchar[]
          AND EXISTS (
            SELECT 1 FROM auth_audit_events AS a
            WHERE a.user_id = m.user_id AND a.organization_id = m.organization_id
              AND a.action IN ('owner.provisioned', 'owner.signup')
          )
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute(
        "UPDATE memberships SET permissions = array_remove(permissions, 'organization.setup')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "version")
    op.drop_column("organizations", "configured")
    op.drop_column("organizations", "receipt_footer")
    op.drop_column("organizations", "timezone")
    op.drop_column("organizations", "currency")
    op.drop_column("organizations", "phone")
    op.drop_column("organizations", "contact_email")
    op.drop_column("auth_sessions", "step_up_expires")
    op.drop_column("auth_audit_events", "changes")
    op.drop_column("auth_audit_events", "target_id")
    op.drop_column("auth_audit_events", "target_type")
    op.drop_index(op.f("ix_registers_store_id"), table_name="registers")
    op.drop_table("registers")
    op.drop_index(op.f("ix_stores_organization_id"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
