"""verified email and authenticator enrollment"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "cbb319198c91"
down_revision = "b53cb45c1439"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_mail_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.String(length=8192), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth_email_challenges",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("credential_hash", sa.String(length=64), nullable=True),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_auth_email_challenges_email"), "auth_email_challenges", ["email"], unique=False
    )
    op.add_column(
        "users",
        sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("users", sa.Column("mfa_secret", sa.String(length=512), nullable=True))
    op.add_column("users", sa.Column("mfa_pending", sa.String(length=512), nullable=True))
    op.add_column(
        "users", sa.Column("mfa_pending_expires", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("mfa_last_step", sa.Integer(), nullable=False, server_default="-1")
    )
    op.add_column(
        "users",
        sa.Column(
            "recovery_hashes",
            postgresql.ARRAY(sa.String(length=64)),
            nullable=False,
            server_default="{}",
        ),
    )
    # Backfill legacy users without asserting ownership of their email addresses.
    for column in ("email_verified", "mfa_last_step", "recovery_hashes"):
        op.alter_column("users", column, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "recovery_hashes")
    op.drop_column("users", "mfa_last_step")
    op.drop_column("users", "mfa_pending_expires")
    op.drop_column("users", "mfa_pending")
    op.drop_column("users", "mfa_secret")
    op.drop_column("users", "email_verified")
    op.drop_index(op.f("ix_auth_email_challenges_email"), table_name="auth_email_challenges")
    op.drop_table("auth_email_challenges")
    op.drop_table("auth_mail_outbox")
    # ### end Alembic commands ###
